
	util.AddNetworkString("zs_gamestate")
	
	util.AddNetworkString("zs_item_pac")
	util.AddNetworkString("zs_wavestart")
	util.AddNetworkString("zs_waveend")
	util.AddNetworkString("zs_lasthuman")
	util.AddNetworkString("zs_gamemodecall")
	util.AddNetworkString("zs_lasthumanpos")
	util.AddNetworkString("zs_endround")
	util.AddNetworkString("zs_centernotify")
	util.AddNetworkString("zs_topnotify")
	util.AddNetworkString("zs_hpnotify")
	util.AddNetworkString("zs_getacurse")
	util.AddNetworkString("zs_zvols")
	util.AddNetworkString("zs_nextboss")
	util.AddNetworkString("zs_activate_trinket")
	util.AddNetworkString("zs_deminextboss")
	util.AddNetworkString("zs_update_style")
	util.AddNetworkString("zs_mge_phr")
	util.AddNetworkString("zs_sync_style")
	util.AddNetworkString("zs_golden")
	util.AddNetworkString("zs_code_get")
	util.AddNetworkString("zs_ability_weapon")
	util.AddNetworkString("zs_skills_active_branch")


	util.AddNetworkString("zs_upgrade_trinket")
	

	util.AddNetworkString("zs_last_points")
	
	
	util.AddNetworkString("zs_skill_is_destroyed")
	util.AddNetworkString("zs_classunlock")
	util.AddNetworkString("zs_sigilcorrupted")
	util.AddNetworkString("zs_sigiluncorrupted")
	util.AddNetworkString("zs_survivor")
	util.AddNetworkString("zs_itemstock")
	util.AddNetworkString("zs_playerredeemed")
	util.AddNetworkString("zs_dohulls")
	util.AddNetworkString("zs_penalty")
	util.AddNetworkString("zs_add_p")

	util.AddNetworkString("zs_nextresupplyuse")
	util.AddNetworkString("zs_stowagecaches")
	util.AddNetworkString("zs_nextfridgeuse")
	util.AddNetworkString("zs_fridgecaches")


	util.AddNetworkString("zs_lifestats")
	util.AddNetworkString("zs_lifestatsbd")
	util.AddNetworkString("zs_lifestatshd")
	util.AddNetworkString("zs_lifestatsbe")
	util.AddNetworkString("zs_boss_spawned")
	util.AddNetworkString("zs_champion_all")
	util.AddNetworkString("zs_bounty_add")
	util.AddNetworkString("zs_champion")
	util.AddNetworkString("zs_boss_spawned_merge")
	util.AddNetworkString("zs_boss_slain")
	util.AddNetworkString("zs_demiboss_spawned")
	util.AddNetworkString("zs_demiboss_slain")
	util.AddNetworkString("zs_damageblock")
	util.AddNetworkString("zs_holymantle")
	util.AddNetworkString("zs_commission")
	util.AddNetworkString("zs_healother")
	util.AddNetworkString("zs_healby")
	util.AddNetworkString("zs_buffby")
	util.AddNetworkString("zs_buffwith")
	util.AddNetworkString("zs_repairobject")
	util.AddNetworkString("zs_worldhint")
	util.AddNetworkString("zs_honmention")
	util.AddNetworkString("zs_floatscore")
	util.AddNetworkString("zs_floatscore_vec")
	util.AddNetworkString("zs_zclass")
	util.AddNetworkString("zs_dmg")
	util.AddNetworkString("zs_at_dmg")
	util.AddNetworkString("zs_dmg_prop")
	util.AddNetworkString("zs_legdamage")
	util.AddNetworkString("zs_armdamage")
	util.AddNetworkString("zs_extrastartingworth")
	util.AddNetworkString("zs_ammopickup")
	util.AddNetworkString("zs_ammogive")
	util.AddNetworkString("zs_ammogiven")
	util.AddNetworkString("zs_deployablelost")
	util.AddNetworkString("zs_deployableclaim")
	util.AddNetworkString("zs_deployableout")
	util.AddNetworkString("zs_trinketconsumed")
	util.AddNetworkString("zs_trinketcorrupt")
	util.AddNetworkString("zs_pointsdoubled")
	util.AddNetworkString("zs_nailremoved")
	util.AddNetworkString("zs_remantlercontent")
	util.AddNetworkString("zs_classunlockstate")
	util.AddNetworkString("zs_changeclass")
	util.AddNetworkString("zs_currentround")
	util.AddNetworkString("zs_zsfriend")
	util.AddNetworkString("zs_zsfriendadded")
	util.AddNetworkString("zs_remantleconf")
	util.AddNetworkString("zs_remantleconf_v2")
	util.AddNetworkString("zs_nestbuilt")
	util.AddNetworkString("zs_nestspec")
	util.AddNetworkString("zs_tvcamera")

	util.AddNetworkString("zs_xp_ach")
	util.AddNetworkString("zs_secret")

	util.AddNetworkString("zs_fuckluasend")
	
	util.AddNetworkString("HNS.AchievementsProgress")
	util.AddNetworkString("HNS.AchievementsGet")
	util.AddNetworkString("HNS.AchievementsMaster")
	util.AddNetworkString("zs_medpremium")
	util.AddNetworkString("zs_weaponblocked")
	util.AddNetworkString("zs_xp_damage")

	util.AddNetworkString("zs_block_number")
	util.AddNetworkString("zs_luck")
	util.AddNetworkString("zs_repeat")
	util.AddNetworkString("zs_skillarsenalvoid")

	util.AddNetworkString("zs_mutations_table")

	util.AddNetworkString("zs_inventoryitem")
	util.AddNetworkString("zs_openbounty")
	util.AddNetworkString("zs_trycraft")
	util.AddNetworkString("zs_trygetitem")
	util.AddNetworkString("zs_updatealtselwep")
	util.AddNetworkString("zs_invitem")
	util.AddNetworkString("zs_t_activated")
	util.AddNetworkString("zs_invgiven")
	util.AddNetworkString("zs_wipeinventory")

	util.AddNetworkString("zs_skills_active")
	util.AddNetworkString("zs_skills_unlocked")
	util.AddNetworkString("zs_skills_desired")
	util.AddNetworkString("zs_skill_is_desired")
	util.AddNetworkString("zs_skill_is_unlocked")
	util.AddNetworkString("zs_skills_all_desired")
	util.AddNetworkString("zs_skill_set_desired")
	util.AddNetworkString("zs_skills_init")
	util.AddNetworkString("zs_skills_reset")
	util.AddNetworkString("zs_skills_remort")
	util.AddNetworkString("zs_skills_nextreset")
	util.AddNetworkString("zs_skills_notify")
	util.AddNetworkString("zs_skills_refunded")
	util.AddNetworkString("zs_credit_takepoints")

	util.AddNetworkString("zs_crow_kill_crow")
	util.AddNetworkString("zs_pl_kill_pl")
	util.AddNetworkString("zs_pls_kill_pl")
	util.AddNetworkString("zs_pl_kill_self")
	util.AddNetworkString("zs_death")

	util.AddNetworkString("voice_eyepain")
	util.AddNetworkString("voice_giveammo")
	util.AddNetworkString("voice_death")
	util.AddNetworkString("voice_zombiedeath")
	util.AddNetworkString("voice_pain")
	util.AddNetworkString("voice_zombiepain")

